name: anr
description: Read manga, manhwa, manhua, novels and webtoons in one place.
version: 3.2.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  http: ^1.1.0
  html: ^0.15.4
  intl: ^0.18.1
  mobx: ^2.2.0
  get_it: ^7.6.4
  shimmer: ^3.0.0
  slugify: ^2.0.0
  go_router: ^10.2.0
  flutter_svg: ^2.0.7
  hive_flutter: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_mobx: ^2.0.6+5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.2
  firebase_database: ^10.2.6
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg
    - assets/images/google.svg

flutter_native_splash:
  color: "#fefbff"
  image: assets/images/branding.png
  color_dark: "#1b1b1f"
  image_dark: assets/images/branding.png
  android_12:
    color: "#fefbff"
    image: assets/images/branding.png
    color_dark: "#1b1b1f"
    image_dark: assets/images/branding.png
